repos:
 # Codespell for common misspellings
 - repo: https://github.com/codespell-project/codespell
   rev: v2.3.0
   hooks:
     - id: codespell
       name: Spell Checker (src)
       files: ^(src)/ # Only src and frontend directories
       stages: [pre-commit]
 # Ruff for Python formatting and linting
 - repo: https://github.com/astral-sh/ruff-pre-commit
   rev: v0.7.0
   hooks:
     - id: ruff
       name: Ruff Linter (src)
       args: ["--fix"] # Automatically fix issues
       files: ^src/ # Only src folder
       stages: [pre-commit]
     - id: ruff-format
       name: Ruff Formatter (src)
       files: ^src/ # Only src folder
       stages: [pre-commit]
 # Mypy to check type annotations
 - repo: https://github.com/pre-commit/mirrors-mypy
   rev: v1.0.1
   hooks:
    - id: mypy
      name: Mypy Type Checker (src)
      args: ["--explicit-package-bases"]
      files: ^src/
      stages: [pre-commit]
      language: system